version: '3.8'

services:
  api:
    build: ./api
    ports:
      - '8082:8082' # Port exposé de l'API
    networks:
      - mon-reseau

  client:
    build: ./client
    ports:
      - '3000:80' # Port exposé pour le client React (Nginx écoute sur le port 80)
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge
